### ISSUE TITLE
Solution fails to launch if username/profile path contains spaces

### ISSUE THREAD

**Issue by stewartadam** [OfficeDev/Excel-Add-in-WoodGrove-Expense-Trends#3]
Error I get while attempting to launch debugging:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command "del %LOCALAPPDATA%\Microsoft\Office\16.0\Wef\AppCommands /q" exited with code 1.
```

The directory exists, but when trying to run that command manually I found that `del` or `dir` on `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\AppCommands` fails ('not found') but I *can* `cd` to it.

**Comment by stewartadam** [comment]
Command is not quoted correctly, updating title to reflect that.

**Comment by umasubra** [comment]
Sorry it took so long to respond back.  Thank you so much for submitting the pull request, addressing the issue. We've now incorporated the change in the code. 

Thanks again!
