### ISSUE TITLE
npm ERR! code ENOENT

### ISSUE THREAD

**Issue by ishitadatta** [OfficeDev/Excel-Add-in-WoodGrove-Expense-Trends#6]
I am getting the following error on trying to run this file
![Screenshot (360)](https://user-images.githubusercontent.com/48859631/86615809-9ad66280-bfd2-11ea-9f97-0faec755864d.png)

**Comment by Rick-Kirkham** [comment]
This sample is not a Node.js sample, so it has no package.json file, and you cannot run `npm` commands on it or run it in Visual Studio Code. It is a Visual Studio (not Visual Studio Code) project with a *.sln file. Please read the **Prerequisites** and the **Run the project** sections of the readme file.

**Comment by ishitadatta** [comment]
@Rick-Kirkham I am still getting the following error :
![Screenshot (373)](https://user-images.githubusercontent.com/48859631/87037218-8203c200-c209-11ea-90ef-a2c4852fb6b8.png)
